### PR TITLE
Add --tag flag that allows for specifying a specific version of Zalenium and Docker-Selenium.

### PR DESCRIPTION
**Pull request by bmaher**
This PR introduces the `--tag` flag that allows for specifying a specific version of Zalenium to use. This version will be downloaded from Zalando's open source registry (including the matching Docker-Selenium).

This PR also includes a couple of minor alignment fixes to the help text.

### CODE REVIEW

**Comment by elgalu** [comment]
Cool! Note the reason why `zalenium_tag` is separated from `dosel_tag` is because is two separate projects with separate release cycles so the image tags will not match:

See project tags at:
https://github.com/elgalu/docker-selenium/releases
https://github.com/zalando/zalenium/releases

So in docker-selenium latest tag is `3.13.0-p1` while in Zalenium latest is `3.13.0a`.

**Review by elgalu — CHANGES_REQUESTED** [review]
Split zalenium_tag and dosel_tag as it was or it will not work.

**Comment by bmaher** [comment]
Sure thing, I've split the tags again and verified that all of the cases (3, 2, 3*, 2*, --tag) work as expected.

**Review by elgalu — APPROVED** [review]

**Comment by elgalu** [comment]
👍 nice work!

**Pull request merged**
